version: 1

sequences:
  - protein:
      id: A
      sequence: MALLTLFNQIWQEGQLQSSTSSFNIFLVPILCLSIFILFSLTRSSSPSEKNRKLKLPPSPPRLPWIGNLHQLGSFPHRSLRALSKKYGDVMFMHFGKVPTLIVSSAEMAKDVMKTQDIVFCSRPQTTAPSILFYDGHDIAFAPYGEYWRQVRRICVLELLSLKRVHQFQYARVEEVAELVSKIRKASASANGAPINLGELLVSTSNNIICRCILGQKFEDKEDNWFGETTKELMTQVMSFSFGDFFPSLKWIDRARGYLAYLKSIWLEFDKFFDKLIDEHKAAQKEGKPRKKDIVDILLDVQNDGSLDFELTTSNVKAILQDMFVGGSDTSWTAAIWLMSELSQNPRVMKKVQEEVRRVAGKRGYVEESDINEMKYLTCVIKENLRLHPPAPLLLPREAMSDVKLGGFDIPAKTQVFVNAYAVQRDPKVWDKPDEFMPERFEENNVGFVGQDFELIPFGAGRRVCPGLAFGVASAQYVLANMLYWFDWKLPSGGSKLAETLDMSEVYGLTVHKKSPLYLVPTPYSP
      msa: 0  # use MSA server or provide path if available
  - ligand:
      id: T
      smiles: O=P([O-])([O-])OP(=O)([O-])O.[H][C@@]12C[C@@H](C(C)(C)O)CC[C@@]1(C)CCC=C2C  # multi-fragment, matches full SDF connectivity

templates:
  - sdf: /home/iska/amelie-ai/mora-stage-2/data/product.sdf
    chain_id: T
    atom_map: identical
    force: true
    threshold: 0.005

constraints:
  - pocket:
      binder: T
      contacts: [
        [A, 465]
      ]
      max_distance: 9.0
      force: true

properties:
  - affinity:
      binder: T
